### ISSUE TITLE
Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by janinneweigel** [iinc0gnit0/RVuln#1]
https://imgur.com/tvZzAzs.png

Error in Kali Linux

**Comment by iinc0gnit0** [comment]
The file path that you specified is incorrect

**Comment by janinneweigel** [comment]
Then, how?

**Comment by iinc0gnit0** [comment]
you have to specify the right path to your wordlist. For example: `/usr/share/wordlists/payloads/xss.txt`

**Comment by janinneweigel** [comment]
![image](https://user-images.githubusercontent.com/49048999/87672320-f7890880-c79c-11ea-903a-6d738a0015ab.png)


same

**Comment by iinc0gnit0** [comment]
That was just an example, you have to specific your own wordlist path
